### ISSUE TITLE
build looks like its breaking

### ISSUE THREAD

**Issue by bigsnarfdude** [alexanderdean/Unified-Log-Processing#22]
url module ansible:
    # Equivalent of git cloning tags/v1.6.6 but much, much faster
    url: https://codeload.github.com/ansible/ansible/zip/69d85c22c7475ccf8169b6ec9dee3ee28c92a314
    build: unzip ansible-69d85c22c7475ccf8169b6ec9dee3ee28c92a314.zip
    export: ansible-69d85c22c7475ccf8169b6ec9dee3ee28c92a314

instead of build and unzip use:

unpack: zip

**Comment by alexanderdean** [comment]
Thanks Vincent!
